

import './globals.css'
import { Rubik } from 'next/font/google'




const rubik = Rubik({ subsets: ['latin'] })

/* Diese Metadaten werden für jede Seite angezeigt. Das kann ich ändern, indem ich sie auf der Seite, wo ich sie ändern will, einfüge und ändere/überschreibe. */
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {children}
      </body>
    </html>
  )
}
